version: '3.8'
services: 
  frontend:
    build:
      context: ./react-front-end
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./flask-back-end
      dockerfile: Dockerfile
    ports:
      - "5238:5238"
    depends_on:
      - db2

  db2:
    image: mysql/mysql-server:latest
    environment:
      MYSQL_ROOT_PASSWORD: mc
      MYSQL_DATABASE: AGDev43
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./sql_statement:/docker-entrypoint-initdb.d

  phpmyadmin2:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
      - db2
    environment:
      PMA_HOST: db2
      PMA_USER: root
      PMA_PASSWORD: mc
    ports:
      - "8080:80"

  express:
    container_name: express
    build:
      context: express-back-end
    restart: always
    ports:
      - 3001:3001
    depends_on:
      - db2
